import { siteConfig, slugQuery } from "./lib/sanity/queries";

import DefaultLayout from "./layouts/default";
import Head from "next/head";
import ImageVideoBgComponent from "./components/heros/imageVideoBgComponent";
import { getClient } from "./lib/sanity";
import { groq } from "next-sanity";
import { useRouter } from "next/router";
import TextImageGrid from "./components/textImageGrid/textImageGrid";
import Partners from "./components/partners/partners";
import Card1 from "./components/card/card";
import Newletter1 from "./components/newletters/newletter1";

// Start editing here, save and see your changes.
export default function Slug({ data, preview, errorPage }: any) {
  const router = useRouter();
  if (!router.isFallback && !data?.pages?.slug) {
    //TODO: Create error page component.
    // connect the error page component here and
    // pass the errorPage object as a prop to the error page component
    // then connect the data from within the error page component
    console.log("from here", errorPage);
    return "Error page";
  }
  const content = data?.pages?.content;
  return (
    <DefaultLayout>
      <div className="h-screen">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          {content &&
            content.map((el: any, i: number) => (
              <div key={i} className="h-full">
                {el._type === "imageVideoBgHeroComponent" ? (
                  <ImageVideoBgComponent content={el} />
                ) : el._type === "imageAndTextGrid" &&
                  el.type === "imgLeftTextRight" ? (
                  <TextImageGrid content={el} />
                ) : el._type === "partners" ? (
                  <Partners content={el} />
                ) : el._type === "cardsAndCaptions" &&
                  el.type === "cardsection1" ? (
                  <Card1 content={el} />
                ) : el._type === "newsletter" && el.type === "newsletter1" ? (
                  <Newletter1 content={el} />
                ) : null}
              </div>
            ))}
        </main>
      </div>
    </DefaultLayout>
  );
}

export async function getStaticProps({ params, preview = false }) {
    const slug = params.slug;
    const sQuery = slugQuery(slug);
    const config = siteConfig();

    const paths = await getClient(false).fetch(config);
    const data = paths;

    const ref = data.errorpage;

    const pages = await getClient(false).fetch(sQuery, {
        slug: params.slug
    });

    console.log(ref)

    return {
        props: {
            preview,
            data: { pages },
            errorPage: ref,
        }
    };
}

export async function getStaticPaths() {
    const paths = await getClient(false).fetch(
        groq`*[_type == "page" && defined(slug.current)][].slug.current`
    );

    return {
        paths: paths.map((slug: any) => ({ params: { slug } })),
        fallback: true
    };
}
